name: bluetooth_low_energy
description: 'A Flutter plugin for controlling the bluetooth low energy, supports central and peripheral roles.'
version: 6.1.0
repository: https://github.com/yanshouwang/bluetooth_low_energy
issue_tracker: https://github.com/yanshouwang/bluetooth_low_energy/issues
topics:
  - bluetooth
  - bluetooth-low-energy
  - ble
publish_to: none

environment:
  sdk: ^3.7.2
  flutter: '>=3.7.0'
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  bluetooth_low_energy_platform_interface:
    git:
      url: https://github.com/warioddly/bluetooth_low_energy.git
      path: bluetooth_low_energy_platform_interface
      ref: HEAD
  bluetooth_low_energy_android:
    git:
      url: https://github.com/warioddly/bluetooth_low_energy.git
      path: bluetooth_low_energy_android
      ref: HEAD
  bluetooth_low_energy_darwin:
    git:
      url: https://github.com/warioddly/bluetooth_low_energy.git
      path: bluetooth_low_energy_darwin
      ref: HEAD

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: bluetooth_low_energy_android
      ios:
        default_package: bluetooth_low_energy_darwin
